const BASE_UNIT_G100 = "100 г"
const BASE_UNIT_ML100 = "100 мл"
const BASE_UNITS = [BASE_UNIT_G100, BASE_UNIT_ML100]

const PORTION_UNIT_G = "г"
const PORTION_UNIT_ML = "мл"
const PORTION_UNIT_TEA_SPOON = "ч.л."
const PORTION_UNIT_TABLE_SPOON = "ст.л."
const PORTION_UNIT_PORTION = "порция"
const PORTION_UNIT_PIECE = "шт"
const PORTION_UNIT_SLICE = "ломтик"

const PORTION_UNITS = [PORTION_UNIT_G, PORTION_UNIT_ML, PORTION_UNIT_TEA_SPOON, PORTION_UNIT_TABLE_SPOON, PORTION_UNIT_PORTION, PORTION_UNIT_PIECE, PORTION_UNIT_SLICE]

const PORTION_UNITS_DEFAULT = {}
PORTION_UNITS_DEFAULT[BASE_UNIT_G100] = {}
PORTION_UNITS_DEFAULT[BASE_UNIT_G100][PORTION_UNIT_G] = 0.01
PORTION_UNITS_DEFAULT[BASE_UNIT_ML100] = {}
PORTION_UNITS_DEFAULT[BASE_UNIT_ML100][PORTION_UNIT_ML] = 0.01
PORTION_UNITS_DEFAULT[BASE_UNIT_ML100][PORTION_UNIT_TEA_SPOON] = 0.05
PORTION_UNITS_DEFAULT[BASE_UNIT_ML100][PORTION_UNIT_TABLE_SPOON] = 0.18

const BASE_UNIT_TO_PORTION = {}
BASE_UNIT_TO_PORTION[BASE_UNIT_G100] = PORTION_UNIT_G
BASE_UNIT_TO_PORTION[BASE_UNIT_ML100] = PORTION_UNIT_ML